version: '2'
services:
  mongodb:
    image: 'dsgupc/meshdapp-mongodb'
    network_mode: 'host'
  ganache:
    image: 'trufflesuite/ganache-cli'
    network_mode: 'host'
    command: node /app/ganache-core.docker.cli.js -l 11000000 -i 7775  -m "improve bomb example bus alert argue behind leopard taste champion antique behave"
  prometheus:
    image: 'dsgupc/meshdapp-prometheus'
    network_mode: 'host'
  oracle:
    image: 'dsgupc/meshdapp-oracle'
    network_mode: 'host'
    depends_on: 
      - mongodb
      - ganache
      - prometheus
